// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/database-types';

const SUPABASE_URL = "https://dwirhhaqmgkrwjjabxrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3aXJoaGFxbWdrcndqamFieHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTY2NTUsImV4cCI6MjA3MTk5MjY1NX0.bVHDcnzB4lfdDtvOHDFiU0_HFph4g2aXtNhe9WN0OtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});